### PR TITLE
Update autocomplete.js

### PR DESCRIPTION
**Pull request by miladmeidanshahi**

### CODE REVIEW

**Comment by zslabs** [comment]
Can you explain what `vir-form-search` is? That doesn't look UIkit related if I'm not mistaken - and if so, wouldn't be added for one-off cases.

**Comment by miladmeidanshahi** [comment]
```
vir-form-search
```

it is my custom class name it can be anything.

**Comment by malles** [comment]
So anyone with another custom class should create another PR, stacking it behind yours?

**Comment by miladmeidanshahi** [comment]
generally that class must be ``` uk-dropdown ``` the parent of autocomplete drop down.

**Pull request closed without merging**
