### PR TITLE
[+] uk-dropdown-close class fix for mode:'hover' and manual

### PR DESCRIPTION
**Pull request by VoidVolker**

### CODE REVIEW

**Comment by VoidVolker** [comment]
If use for dropdown option `mode:'click'` - dropdown is hiding after user's click. But if this option 'hover' - it not hides. This commit is fixing this problem.
Also, added description of uk-dropdown-close class into documentation.

**Comment by aheinze** [comment]
please fork and create a pull request for the develop branch, thanks!

**Comment by VoidVolker** [comment]
Ah, I do it for master? My wrong ) Ok, I do.

**Comment by VoidVolker** [comment]
Closing. Reason: re-creating of pull-request more correct way into dev branch.

**Pull request closed without merging**
