### PR TITLE
[Feature] Checkbox and radio toggle switch for adv forms

### PR DESCRIPTION
**Pull request by Evanion**
Adds toggle switch styled inputs for checkbox and radio buttons.
This implementation is CSS only, with minimal markup needed.

Modifiers:
- Style (success, warning, danger) - based on global colours.
- Size (small, large) - based on input field

### CODE REVIEW

**Comment by Evanion** [comment]
Here is a [screenshot](https://photos-4.dropbox.com/t/2/AADDGvVyvpCC87BprVzOPDWHqbi0J7A-xisPTEqaAos6hA/12/38646668/png/32x32/1/_/1/2/Screenshot%202015-10-29%2008.49.25.png/EL66uh0Ypd0pIAcoBw/cLIfXfcK6QHEKFNICy9o6xat3hUSpTZwcjiksBbdI-A?size=1280x960&size_mode=2) of the functionality

**Comment by robertotremonti** [comment]
That's a great addition.
I'd like to see it added to main branch.

**Comment by Evanion** [comment]
I still need to do some work though.. the Less code could use some tidying up ... and I was hoping to find a UIkit Styleguide for it ...

**Comment by mojtabakaviani** [comment]
+1

**Comment by Linfuby** [comment]
+1

**Comment by o15s19** [comment]
+1

**Comment by ZeGregg** [comment]
Hope to see this in the main branch +1

**Comment by dtdpro** [comment]
Great addition +1

**Comment by philoest** [comment]
UIKit version 2 has been moved to another branch: https://github.com/uikit/uikit/tree/v2/develop

Please update the target branch of your pull request.

**Pull request closed without merging**
