### PR TITLE
Rework use of uk-overlay-icon to require an associated uk-icon-* class

### PR DESCRIPTION
**Pull request by bbenne10**
See #1419 for further explanation. If there's a better way of handling this, I think discussing it here is the best way forward.

### CODE REVIEW

**Comment by gabrielholley** [comment]
I'm not sure a requirement to use uk-icon-* is the best here. While I do want the ability to use uk-icon-*, as that often does come up, not having a default is cumbersome as well.

Instead of removing @overlay-icon, we could use this instead:

```
.uk-overlay-icon:not([class*='uk-icon-']):before {
    content: @overlay-icon;
}
.uk-overlay-icon:before {
    position: absolute;
    top: 50%;
    left: 50%;
    width: @overlay-icon-size;
    height: @overlay-icon-size;
    margin-top: -(@overlay-icon-size / 2);
    margin-left: -(@overlay-icon-size / 2);
    font-size: @overlay-icon-size;
    line-height: 1;
    font-family: FontAwesome;
    text-align: center;
    color: @overlay-icon-color;
    .hook-overlay-icon;
}
```

Therefore, when not using .uk-icon-*, the default @overlay-icon is still used, and not enforcing an icon selection for each overlay icon.

**Comment by bbenne10** [comment]
While I disagree that it's any more cumbersome to explicitly add the icon you want to use, this also works just fine. I'm not sure about performance of the attribute prefix selector, but I don't think that should be too much of a problem. It'd be nice to get some feedback from someone with write privileges though.

**Comment by philoest** [comment]
UIKit version 2 has been moved to another branch: https://github.com/uikit/uikit/tree/v2/develop

Please update the target branch of your pull request.

**Comment by bbenne10** [comment]
Unless I receive feedback on the general approach I'm taking, I fail to see the usefulness of taking the time to update the target branch. This ticket has been open for over a year with no feedback, which is ridiculous in itself, and then both the issue is closed because the team wanted a clean slate. I apologize if this seems petty, but I'm busy enough as it is and I refuse to do additional work until it's clear that my work will be thoughtfully considered by those that have power to do something about it.

**Pull request closed without merging**
