### PR TITLE
Active count should never be negative.

### PR DESCRIPTION
**Pull request by jbenesch**
if (!activeCount) only ever fires if activeCount is 0. We were getting activeCount being a negative number which was causing issues because $html.removeClass("uk-modal-page"); was never being called which was locking up the window.

activeCount should never be negative.

### CODE REVIEW

**Comment by zslabs** [comment]
@aheinze I believe we ran into this when we were calling `Uikit.modal(selector).hide()` more times than we were showing it, but if you get to a negative number you're essentially screwed ;)

**Comment by jbenesch** [comment]
It's a timing issue. If you call .hide() and then .show() immediately after, the show method calls .hide(true) which forces a hide and the first .hide() call finally gets processed during this event: UI.support.transition.end which causes the activeCount to go negative.

**Comment by jbenesch** [comment]
You can recreate the issue by going here: http://getuikit.com/docs/modal.html

And in the console enter this: ```UIkit.modal('#modal').show(); UIkit.modal('#modal').hide();```

Now try and scroll, or click, or just interact with the window in general.

**Comment by jbenesch** [comment]
Ok I got to the bottom of this one. If removeClass('uk-open') gets called before the addClass('uk-open') modal transition has happened, then UI.support.transition.end never actually fires and this._hide() never gets run.

Proposed change adds a hasTransitioned property to the modal component. If client supports transition, we attach a one time event listener when we add class to switch the hasTransitioned flag. Then in the hide method, we check to see if the open transition has happened or not to decide whether we should try and transition out the modal or just force close it.

**Comment by aheinze** [comment]
Thanks!

**Pull request merged**
