### PR TITLE
Hotfix height viewport when top is less than zero

### PR DESCRIPTION
**Pull request by ivanmatiaspascual**
I have cases where top can be 0, less than 0 or more than 0.

### CODE REVIEW

**Comment by janschoenherr** [comment]
What Chrome version are you having trouble with?

    calc(50px - -150px - 30px)

seems to be correctly evaluating to

    170px

**Comment by ivanmatiaspascual** [comment]
There is not syntax problem, sorry, the problem is because of my case is like that: 
calc((100vh - -57px) - 0px) 
and i think it should be like that: 
calc((100vh - 57px) - 0px).

My case is a bit more complex that the example here, if you need to see the whole case i can show you the behavior with a video even show you the updates of the function i both cases (with and with out the change).

**Comment by janschoenherr** [comment]
Could you somehow simplify it in a codepen example?

**Comment by ivanmatiaspascual** [comment]
I have reorganized my forked repository to support one of your version. I still want to share this case with you. When i take the time i will show you with codepen example. See you later.

**Comment by ivanmatiaspascual** [comment]
Fix at Commit f12b3039 by janschoenherr, 07/25/2019 04:57 AM

**Pull request closed without merging**
