### PR TITLE
Re-compress png images losslessly using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use Google's zopflipng to re-compress/optimize the png images to smaller sizes, 7 png images optimized as below:

```
 docs/images/apple-touch-icon.png      | Bin 3703 -> 2107 bytes
 docs/images/layouts_blog.png          | Bin 54352 -> 47434 bytes
 docs/images/layouts_contact.png       | Bin 43891 -> 32908 bytes
 docs/images/layouts_documentation.png | Bin 66861 -> 57177 bytes
 docs/images/layouts_frontpage.png     | Bin 64388 -> 55931 bytes
 docs/images/layouts_login.png         | Bin 9154 -> 7283 bytes
 docs/images/layouts_portfolio.png     | Bin 21110 -> 17374 bytes
```

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@janschoenherr any reason to close it without any comment?

**Comment by PeterDaveHello** [comment]
Hello @janschoenherr ?

**Comment by philoest** [comment]
Sorry for the inconvenience UIKit version 2 has been moved to another branch: https://github.com/uikit/uikit/tree/v2/develop which automatically closed all PRs to the old branch.

Please update the target branch of your pull request.

**Comment by PeterDaveHello** [comment]
@philoest could you please help reopen so that I can update target branch?

**Comment by PeterDaveHello** [comment]
@philoest should be good now?

**Comment by aheinze** [comment]
Thanks!

**Pull request merged**
