### PR TITLE
Re-compress jpg images losslessly using jpegoptim

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use jpegoptim to re-compress/optimize the jpg images to smaller sizes, 7 jpg images optimized as below:

```
 docs/images/placeholder_800x400_1.jpg | Bin 45412 -> 44248 bytes
 docs/images/placeholder_800x400_2.jpg | Bin 47895 -> 46901 bytes
 docs/images/placeholder_800x400_3.jpg | Bin 40007 -> 39217 bytes
 docs/images/placeholder_800x600_1.jpg | Bin 122389 -> 120184 bytes
 docs/images/placeholder_800x600_2.jpg | Bin 122079 -> 120181 bytes
 docs/images/placeholder_800x600_3.jpg | Bin 107110 -> 105839 bytes
 docs/images/placeholder_800x600_4.jpg | Bin 219124 -> 216056 bytes
```

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@janschoenherr any reason to close it without any comment?

**Comment by philoest** [comment]
UIKit version 2 has been moved to another branch: https://github.com/uikit/uikit/tree/v2/develop

Please update the target branch of your pull request.

**Comment by PeterDaveHello** [comment]
@philoest since it's close my maintainer, I can't just re-open to update target branch.

**Comment by PeterDaveHello** [comment]
The new optimization on new code base is too few, ignore that.

**Comment by PeterDaveHello** [comment]
@philoest updated.

**Comment by aheinze** [comment]
Thanks!

**Pull request merged**
