### PR TITLE
Fix: Error in table.less component - Function round must be a number

### PR DESCRIPTION
**Pull request by inyunussenem**
Hello, pull request for the problem opened in issue

### CODE REVIEW

**Comment by AlekVolsk** [comment]
What is this nonsense? How am I supposed to understand when setting a variable what 16 means? 16px? 16rem? 16$?

**Comment by ynswtf** [comment]
> What is this nonsense? How am I supposed to understand when setting a variable what 16 means? 16px? 16rem? 16$?

You are right, maybe you want to fix it?

**Comment by miloslavkostir** [comment]
Hi, I think this is not the problem.

Expression must be in parenthesis:
```
round(@table-cell-padding-vertical / 3)  // Error - must be number
round((@table-cell-padding-vertical / 3))  // This works
```
https://github.com/uikit/uikit/issues/4409

**Comment by saschadube** [comment]
Is this a Less bug? Unfortunately I can't find anything about why there has to be extra parenthesis in their documentation. Am I missing something?

**Comment by janschoenherr** [comment]
Thanks, fixed with 3.9.1

**Pull request closed without merging**
