### PR TITLE
Use Gulp and Preprocessor to Build Documentation

### PR DESCRIPTION
**Pull request by DerekTBrown**
THIS IS NOT YET COMPLETED

I am working to integrate a preprocessor into the documentation, which should make adding pages and editing them much easier.

### CODE REVIEW

**Comment by DerekTBrown** [comment]
A couple more tasks left:

1) Update the title using a preprocessor variable
2) Update the main menu "uk-active" property
3) Add proper JS includes to the top of each page

**Comment by DerekTBrown** [comment]
Above tasks are complete.  Ready for user testing!

**Comment by malles** [comment]
It looks real nice as a concept. We'd have to study this more though.

**Comment by DerekTBrown** [comment]
@janschoenherr why are you closing this?

**Comment by philoest** [comment]
UIKit version 2 has been moved to another branch: https://github.com/uikit/uikit/tree/v2/develop

Please update the target branch of your pull request.

**Pull request closed without merging**
