### PR TITLE
feat: Adds responsive flex direction and v-alignment

### PR DESCRIPTION
**Pull request by KaitaniLabs**
I need these for my project and baked them up. Could be handy for others, especially responsive flex direction.

### CODE REVIEW

**Comment by SuperKrevette** [comment]
Hi @janschoenherr, can you tell us when it will be added to Uikit?

**Comment by SuperKrevette** [comment]
When will it be available for everyone please?

**Comment by infa-abiczews** [comment]
I just looked for that and discovered this thread. It would be quite valuable to have it in the library out of the box.

**Comment by SuperKrevette** [comment]
Hello. October 2020. 
I think the suggestions are never read by the Uikit developers. There is no point in suggesting ideas. They never read them. It has been almost 3 years that means they didn't even take the time to read yours topics. Not even a reply. Nothing. Nada. **What a shame.**

**Comment by zilurrane** [comment]
This is much needed

**Comment by KaitaniLabs** [comment]
I imagine it might make an appearance in v4 perhaps.

**Comment by saschadube** [comment]
It will be added with the next UIkit release

https://github.com/uikit/uikit/commit/c1b6e5455371b3237f81e04a4a7919062f07991d

https://github.com/uikit/uikit/commit/3fb4522338b9234ff0a480e9f08e0843e5f48b89

**Pull request closed without merging**
