### PR TITLE
border-box by default

### PR DESCRIPTION
**Pull request by zslabs**
I've pushed for this a few times, so decided to go ahead and create a PR for it. I think [CSS Tricks](http://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/) says it best, but `box-sizing: border-box` has become the universal standard for base styles to use. I've left all `box-sizing` attributes that require overrides (which is exactly how it should be) and only inherit down `border-box` to components that don't override them.

This makes UIkit smaller and smarter with saner defaults and proper inheritance.

### CODE REVIEW

**Comment by malles** [comment]
Seems a sane thing to do.
One note; you only added the FF prefix for the `*, *:after, *:before` selector.

**Comment by zslabs** [comment]
Thanks @malles - added.

**Comment by zslabs** [comment]
@malles Think that's also something that needs to be addressed -- I use [Autoprefixer](https://www.npmjs.com/package/gulp-autoprefixer) in all my projects without any issues, they've moved it in and out a few times now and I think this is another use-case of it just not being needed.

**Comment by aheinze** [comment]
there is still one problem...imagine the scenario, when uikit is included with a plugin e.g. for the backend. normally you compile uikit without base.less to not mess up the existing css and only use the uikit components. this wouldn't be possible anymore with this PR.

**Comment by zslabs** [comment]
@aheinze I appreciate the response. The only thing I could respond to with that is the idea that `border-box` has become all but a standard in web development nowadays. `content-box` brings us back to the days of IE7 support where width calculations were an utter nightmare.

I can fully understand that UIkit doesn't want to step on the toes of any existing styles that are going on in a page, but think that this one is more a sanity check of what is assumed to be the proper defaults nowadays. `content-box` is basically a left-over from darker days in web dev. I'd appreciate at the very least a quick poll to see who would be opposed to this. Thanks as always man!

**Comment by krzksz** [comment]
IMHO [this](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/) techique would be better.

**Comment by zslabs** [comment]
@krzksz That's what mine does...

**Comment by krzksz** [comment]
@zslabs OMG you're right, I must have overlooked it. I'm sorry. Anyway +1 to this in this form, which lets you set `border-box` for seperate components easylly.

**Comment by zslabs** [comment]
@saschadube I'm happy to amend this to get it up to speed with the current `develop` branch, but believe there is great value in assuming `border-box` by default and letting 3rd party components (or UIkit's when needed) override that behavior.

**Comment by zslabs** [comment]
@saschadube @aheinze Where do we stand on the discussion of simplifying UIkit's base style set? We need smarter defaults, taking advantage of CSS pre-proecessors as they are done in the themes themselves.

**Comment by badpenguin** [comment]
is it safe to add this by default? or it will breaks the responsive grid?

**Comment by philoest** [comment]
UIKit version 2 has been moved to another branch: https://github.com/uikit/uikit/tree/v2/develop

Please update the target branch of your pull request.

**Pull request closed without merging**
