### PR TITLE
fix(icon): make SVG icons non-focusable in IE

### PR DESCRIPTION
**Pull request by fkm**
* https://github.com/PolymerElements/iron-iconset-svg/issues/46
* https://allyjs.io/tutorials/focusing-in-svg.html

### CODE REVIEW

**Comment by janschoenherr** [comment]
Thank you, could you remove the dist files from the pull request?

**Comment by fkm** [comment]
Yes. I wasn't sure what to include. I'll remove the files shortly.

**Comment by anehx** [comment]
@janschoenherr could this be merged?

**Comment by fkm** [comment]
Is there something missing that prevents this from being merged?

**Comment by janschoenherr** [comment]
Thanks, this should work with the latest dev version.

**Comment by fkm** [comment]
Thank you!

**Pull request merged**
