### PR TITLE
add Chips for tags and contacts

### PR DESCRIPTION
**Pull request by WalterC87**
add Chips that can be used to represent small blocks of information, can be used for show contacts or tags

### CODE REVIEW

**Comment by nblackburn** [comment]
What is the difference between this and a badge?

**Comment by nblackburn** [comment]
What is the difference between this and a badge?

**Comment by WalterC87** [comment]
The difference between this and badge is, the badge will be use only for numbers not for text, with the chips, you will be able to put just text or text with an image, these will be cool for contacts info or tags.

**Comment by nblackburn** [comment]
I have used badges with text in the past and they work fine, do you have an image of one so i can better understand the benefit here?

**Comment by nblackburn** [comment]
I have used your source to produce an example to better understand but feel it would better to extend badges to support images as they are mostly the same in functionality and purpose.

**Comment by WalterC87** [comment]
If you do that you will be mixing apples with pears, a badge it's very very different, but if you want to do that, go on.

**Comment by nblackburn** [comment]
By tags did you by any chance mean autocomplete, i think i see what you mean now it was just the examples that threw me off.

**Comment by zzseba78** [comment]
You mean something like this: https://getmdl.io/components/index.html#chips-section
"Represents complex entities in small blocks."

**Comment by nblackburn** [comment]
@zzseba78 Looks like it, the only issue is that they are styled almost exactly the same which doesn't really fit with the default look of UIKit and i am pretty sure `!default` is a sass feature.

**Comment by WalterC87** [comment]
Sorry, I'm new with less I thought that property works for less to, it's my bad, sorry.

**Comment by nblackburn** [comment]
No worries, you can push a change to your branch and this will update automatically.

**Comment by philoest** [comment]
UIKit version 2 has been moved to another branch: https://github.com/uikit/uikit/tree/v2/develop

Please update the target branch of your pull request.

**Pull request closed without merging**
