### PR TITLE
Fixed wrong event name

### PR DESCRIPTION
**Pull request by Skullbock**

### CODE REVIEW

**Comment by malles** [comment]
screenshot_35
That should really be the last one. The only occurences I can still find are in the changelog.

**Comment by Skullbock** [comment]
Should be fixed: https://github.com/Skullbock/uikit/commit/dd7918cf176268b8935835edf5eebcc531cd86e8#diff-8440e422e4ff4a122753581756bbe6f6R380

**Comment by malles** [comment]
:+1:

**Comment by aheinze** [comment]
thanks!

**Pull request merged**
