### PR TITLE
fix(scss): replace deprecated slash division with multiplication

### PR DESCRIPTION
**Pull request by anehx**
https://sass-lang.com/documentation/breaking-changes/slash-div

### CODE REVIEW

**Comment by anehx** [comment]
This resolves #4467

**Comment by brandonbuttars** [comment]
@anehx thanks for doing this.  I would definitely follow @C-Lodder 's suggestion.  I'd love to get his merged.  I'm actually trying to clean up the noise in my build and this is some of it.

**Comment by anehx** [comment]
@brandonbuttars Sounds good, I'll try to find some time to do that!

**Comment by anehx** [comment]
@brandonbuttars It's done! Some calculations won't be as exact as before but I think that's a non-issue, e.g `@xy / 3` will now be `@xy * 0.333` which is not exactly the same. My bigger concern is how we prevent that new code uses slash division, any ideas?

**Comment by janschoenherr** [comment]
Thanks, this will be fixed with the next release.

de0c5f5

**Pull request closed without merging**
