### PR TITLE
Fix/svg animations

### PR DESCRIPTION
**Pull request by szabocsabasandor8000**
When you load the page:
- the SVG animations which are on the screen it work
- the SVG animations which aren't on the screen it don't work. 

This fix will resolve, when you load the page, those SVG animations which are not visible on the screen, will work also.

### CODE REVIEW

**Comment by szabocsabasandor8000** [comment]
I updated the description.

**Comment by janschoenherr** [comment]
Could you add a reproduction link, that shows the issue?

**Comment by szabocsabasandor8000** [comment]
https://i-mediadesign.de/logos
When you scroll down, you will some some SVG animation stopped. But if you refresh the page those SVG animations will work.

**Comment by janschoenherr** [comment]
That seems to be partially copied from the customizer preview in YOOtheme Pro. In general, you'd want to ensure, the scrollspy isn't targeting a large section, but rather smaller parts that contain the SVG.

**Comment by szabocsabasandor8000** [comment]
I understand, but if I don't include the uikit.js bundle file, it works.

**Comment by lzudor-omnitech** [comment]
Hi @janschoenherr ,

Let me jump in here real quick - sorry for the confusion created, I just deleted the given branch & created a clean pull request:
https://github.com/uikit/uikit/pull/4941

Let me know if You have any questions!

Best,
- Lorand.

**Pull request closed without merging**
