### PR TITLE
Style broken for input["submit"] and input["button"] on iOS

### PR DESCRIPTION
**Pull request by tkcent**
Fix for #2558

### CODE REVIEW

**Comment by mattfletcher** [comment]
This is still an issue. Can it be merged?

**Comment by AlekVolsk** [comment]
I don’t think it will be merged, if you need to - just put an additional class on the tag and make it up yourself

**Comment by mattfletcher** [comment]
I do, but I don't get why it's not been merged after so long. It makes UIkit forms look awful on iOS devices.

**Comment by AlekVolsk** [comment]
You may not have noticed, but uikit developers never merge edits suggested by users

**Comment by saschadube** [comment]
@mattfletcher Why not just use the `<button>` element?

**Comment by tkcent** [comment]
@saschadube Sometimes when integrating with a CMS you don't have control over certain default elements.

**Comment by saschadube** [comment]
It will be added to the next release. See https://github.com/uikit/uikit/commit/ce2601e84a6ae0228f6c3c8d138883f027365623

**Pull request closed without merging**
