### PR TITLE
add Class modal dialog

### PR DESCRIPTION
**Pull request by KarimQaderi**
UIkit.modal.confirm('UIkit confirm!', {
            addClass: "newModel"
        }).then(function () {
            console.log('Confirmed.')
        }, function () {
            console.log('Rejected.')
        });

### CODE REVIEW

**Comment by SuperKrevette** [comment]
+1... I have already asked for this... Very usefull for front-end developers too.

**Comment by gregBerthelot** [comment]
Sure, that would be awesome to be able to design dialog in a different way than other modals

**Comment by janschoenherr** [comment]
With the next release the promise object returned by Modal Dialogs holds a reference to the Modal component itself. Does this help you?

https://github.com/uikit/uikit-site/commit/058dd17e7f654596317816ed5822cab071606c7f

**Comment by KarimQaderi** [comment]
yes 
tnx

**Pull request closed without merging**
