### PR TITLE
Fix problems with finite sliding

### PR DESCRIPTION
**Pull request by technik-kvz**
See #4034 

We realized that the problem with finite sliding (for us) were the paddings of the cards. Using them in width calculation fixed the problem with finite sliding.

I did not change the existing getWidth function, since I am not sure if that would break something somewhere else, maybe someone with more knowlege in the uikit details could even change that function.

### CODE REVIEW

**Review by janschoenherr — COMMENTED** [review]
I believe padding is already included in `dimensions(el).width`.

**Comment by technik-kvz** [comment]
I don't see it: 

https://github.com/uikit/uikit/blob/12e41a407f52265eca4c428c749e30a1a89f37d6/src/js/util/dimensions.js#L9

Dimensions is using a getBoundingClientRect if available, which **should** use the padding.  That's right.

But there is this code if "isElement" is failing, which only uses hight and width.

I will run some tests, if I run into that code.

**Comment by technik-kvz** [comment]
I did some research, it always uses the right dimension calculation, so changing the dimensions or width is not neccesary.

But i realized a strange behaviour:

When I change uikit.css:

```
/* Desktop and bigger */
@media (min-width: 1200px) {
  /* Horizontal */
  .uk-grid {
    margin-left: -40px;
  }
  .uk-grid > * {
    padding-left: 40px;
  }
  /* Vertical */
  .uk-grid + .uk-grid,
  .uk-grid > .uk-grid-margin,
  * + .uk-grid-margin {
    margin-top: 40px;
  }
}
```


TO

```
/* Desktop and bigger */
@media (min-width: 1200px) {
  /* Horizontal */
  .uk-grid {
    **margin-left: -39px;**
  }
  .uk-grid > * {
    padding-left: 40px;
  }
  /* Vertical */
  .uk-grid + .uk-grid,
  .uk-grid > .uk-grid-margin,
  * + .uk-grid-margin {
    margin-top: 40px;
  }
}
```


The Problem is gone, too.

There is still something wrong with the "finite" calculation, but not because of the items of the ul. The problem seems to be somewhere between ul and its dimensions/margins.

**Comment by technik-kvz** [comment]
Changed the PR.

It gets weirder, for me a ceil in getWidth solves the problem, too - maybe there is something wrong with the rounding.

There allready is a ceil(...), but on the result of getWidth, not inside of the "reduce" function.

Is there a logical error or is this just coincidence?

**Comment by technik-kvz** [comment]
Yes it solves the problem, thank you very much!

**Pull request closed without merging**
