### PR TITLE
Icon: external link icon added

### LINKED ISSUE #3667: Icon: External link
Please support the external link icon

### PR DESCRIPTION
**Pull request by akshaybabloo**
I am not sure if I have to build the `dist/` and commit it, for now, this has only the SVG file.

Fixes #3667

### CODE REVIEW

**Comment by tonypiper** [comment]
there's a typo in the filename - should be `external-link.svg`

**Comment by akshaybabloo** [comment]
Thanks, @tonypiper. Updated.

**Comment by drmzio** [comment]
I had a PR #3582  for the exact same icon but no luck...

**Comment by akshaybabloo** [comment]
Should have seen that. No idea why that's not been merged

**Comment by akshaybabloo** [comment]
Closing it as there is no response from the maintainers.

**Pull request closed without merging**
