### PR TITLE
fix:4467 Remove / for division due to deprecation

### PR DESCRIPTION
**Pull request by dgrahn**
Fix for https://github.com/uikit/uikit/issues/4467.

I believe this covers all relevant divisions.

### CODE REVIEW

**Review by felixheidecke — APPROVED** [review]
I does indeed LGTM.

**Comment by YassineGherbi** [comment]
Any idea when this will be merged/released?

**Comment by dgrahn** [comment]
@YassineGherbi I don't have the permissions to do that.

**Comment by sly7-7** [comment]
@janschoenherr kindly ping, do you think this could be merged ?

**Comment by jastako** [comment]
This warning is really annoying. Obscures real problems. Any idea when this could get merged? Thanks

**Review by dmitrystas — APPROVED** [review]

**Comment by janschoenherr** [comment]
Fixed with 3.9.1

**Comment by jastako** [comment]
Thank you!

**Pull request closed without merging**
