### PR TITLE
Fixed wrong event name

### PR DESCRIPTION
**Pull request by Skullbock**

### CODE REVIEW

**Comment by malles** [comment]
These should really be the last one of those....
Could you create PR's to the master, they won't be able to merge this.

**Comment by malles** [comment]
These lines have been changed in the current develop branche.

**Comment by aheinze** [comment]
please make PRs only for the develop branch. thanks!

**Comment by Skullbock** [comment]
whoops sure

**Comment by malles** [comment]
And this has not been changed yet in develop, you're right
This table with events is in the doc twice, https://github.com/uikit/uikit/blob/develop/docs/scrollspy.html#L499 and https://github.com/uikit/uikit/blob/develop/docs/scrollspy.html#L363
The one ~363 is not fixed yet.

**Comment by Skullbock** [comment]
Opened a new pull request at https://github.com/uikit/uikit/pull/998

**Comment by malles** [comment]
And there is a bonus on line 380: https://github.com/uikit/uikit/blob/develop/docs/scrollspy.html#L363
Could you fix that one as well?

**Comment by Skullbock** [comment]
Done :)

**Pull request closed without merging**
